name: Trigger auto deployment for faces-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/faces-api-AutoDeployTrigger-1b039e1d-7dec-42ec-8916-ee444bdbc7da.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: jelyid.azurecr.io
          username: ${{ secrets.FACESAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.FACESAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jelyid.azurecr.io/faces-api:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FACESAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n faces-api -g jelyid --server jelyid.azurecr.io --username  ${{ secrets.FACESAPI_REGISTRY_USERNAME }} --password ${{ secrets.FACESAPI_REGISTRY_PASSWORD }}
            az containerapp update -n faces-api -g jelyid --image jelyid.azurecr.io/faces-api:${{ github.sha }}
